# Generated by Django 2.2 on 2020-04-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item Name')),
                ('num_count', models.BigIntegerField(verbose_name='Count Number')),
            ],
            options={
                'verbose_name': 'Count Info',
                'verbose_name_plural': 'Count Info',
                'db_table': 'count_info',
            },
        ),
    ]
